### ISSUE TITLE
Task 1 Wiki typo

### ISSUE THREAD

**Issue by lm-t** [urig/python-exercise#1]
Theres a typo. Instead of "implement a method called hello_world()" it should be "implement a method called helloWorld()" otherwise the tests will throw an attribution error.

**Comment by urig** [comment]
Thank you. Will look into it and fix as soon as I can spare the time.

**Comment by urig** [comment]
@lm-t thanks again. I fixed the issue the other way around - by renaming the method name in the test to match python naming convention: `hello_world()`.
